### ISSUE TITLE
服务器

### ISSUE THREAD

**Issue by LiCryptoX** [HuQi2018/Douban-Explorer#1]
请问一下服务器端的数据是无法使用了么？我现在打开前端网页显示服务器端有错误？

**Comment by HuQi2018** [comment]
嗯，我的数据库修改了，你可以自己本地创建一个MongoDB数据库，然后修改下配置并在数据库中创建好相关表，具体可参照附件：安装说明书.pdf
弄好配置后默认都是0，这时可以用搜索功能为数据库添加数据。
当然也可以自己通过另写的爬虫循环往数据库中存入数据。

**Comment by LiCryptoX** [comment]
嗯好的，那在请问一下服务器端使用的是mongodb数据库，本地是redis吗？意思是需要下载这两个数据库吗？我还是个小白，希望能够学习下这个项目

**Comment by HuQi2018** [comment]
MongoDB、redis都可以放本地，如果放在服务器上就需要开启外网访问权限，需要配置下才行，你可以先学着在本地搭建。数据库搭建完还需要修改web（后端服务）文件夹中的：
1.修改mongodb的连接配置：\web\web\settings.py
2.修改redis的连接配置：\web\utils\redis_pool.py
配置文件。

同时你运行的python环境中要安装相关所需的库。可以在web目录下使用命令：
3.安装所需的Python库：在\web目录下执行 pip install --index https://mirrors.aliyun.com/pypi/simple/ -r requirements.txt

最后将后端服务启动：
4.启动Django服务：在\web目录下执行 python .\manage.py runserver
如果最后没报错就代表成功了。

**Comment by LiCryptoX** [comment]
恩非常感谢。那我就把两个数据库都下在本地，然后放入数据使用，那些库我都装了，我后面就是先把两个数据库配置好。

**Comment by HuQi2018** [comment]
[MongoDB数据库文件](https://pan.baidu.com/s/1rh-l0PLnldUXyBCJCtcN5w)
提取码：n86j
把这个下载下来，将其所有文件放置/替换你的MongoDB的test数据集目录，就可以用我的数据集了

**Comment by LiCryptoX** [comment]
OKOK，我马上下载下来试试。麻烦了哦

**Comment by LiCryptoX** [comment]
你好，我又有一个小白问题来请教了。就是我有两个数据库mongodb和redis那么这两个各自使用来干啥的呢？我替换了那些文件发现没有用。。这两个数据库各自是干啥的呢？

**Comment by HuQi2018** [comment]
MongoDB用来存储爬取的原始数据。
Redis用来缓存前端读取的图表数据，加快第二次访问，同时减轻服务器的运行压力。

**Comment by LiCryptoX** [comment]
哦哦哦，意思是redis在后面前端的借口中才会用到吧

**Comment by HuQi2018** [comment]
要运行起来就必须都要配置好，redis一开始没数据的只要搭建好配置端口修改好就可以，昨天那个网盘里的是MongoDB里的数据。

**Comment by LiCryptoX** [comment]
嗯我就是把你给我的那个数据放到了mogondb/data文件里，但是不知道为啥数据库里数据没有出来，我现在还在研究勒哈哈哈

**Comment by HuQi2018** [comment]
你可以用Robo 3T工具连上去看看

**Comment by HuQi2018** [comment]
你可以用Robo 3T工具连上去看看

**Comment by LiCryptoX** [comment]
哈哈我用的是mongodb compass，它自带的那个

**Comment by LiCryptoX** [comment]
请问下是简单地将您给我的文件复制到mongodb/data文件夹下就可以了吗？还是说要配置啥的

**Comment by HuQi2018** [comment]
所有文件同样也是在mongodb/data/test，test目录不要少哦

**Comment by LiCryptoX** [comment]
哎哟，我少了个test，我看看喃

**Comment by HuQi2018** [comment]
呃，有些日志文件也要替换，忘记了，重新上传了你再试试。

[MongoDB数据库文件](https://pan.baidu.com/s/1CuwFU5BT-Z0sfxKsRkwihw) 提取码: b8f2 
将其所有文件放置/替换MongoDB的\data\test数据集目录，同时将data.tar.gz解压到\data下替换所有，最后admin、test、config、root等都在同一个目录，即可使用。

**Comment by LiCryptoX** [comment]
哈哈哈哈,特别感谢你，我再下载下来试试。

**Comment by HuQi2018** [comment]
close
